HA0, Орлова Саша
adkozlov/scala-2018 pull request #110
Opened 2018-12-25 18:25 UTC by SashaOrlova

Добрый день, задачи из https://projecteuler.net/archives с указанными номерами в качестве названия файлика. Каждый файлик представляет собой отдельное решение, не имеющее зависимостей с другими файлами

2018-12-27 09:47 UTC, adkozlov requested changes
Сделайте, пожалуйста, до вечера так, чтобы это собиралось средой разработки.

2018-12-27 09:47 UTC, adkozlov commented on EulersProblems/src/main/scala/Problem401.scala
> +  def TestProblem(): Unit = {
Тесты лучше было бы оформить именно в виде тестов.

2018-12-27 09:47 UTC, adkozlov commented on EulersProblems/src/main/scala/Problem401.scala
> +sealed trait Bool {
Все эти общие типы тоже можно было бы в одном месте определять.

2018-12-27 09:47 UTC, adkozlov commented on EulersProblems/src/main/scala/Problem401.scala
> +sealed trait Bool {
Более того, это не собрать IntelliJ IDEA.

2018-12-27 13:35 UTC, SashaOrlova commented
Исправила, теперь собирается

2018-12-28 14:24 UTC, adkozlov commented on EulersProblems/src/main/scala/Problem401.scala
> +  sealed trait Nat {
Я уже говорил, что все комментарии могут применяться не к одному месту, а к проекту в целом.
Можно заметить, что `Nat`, `Succ`, `Zero` тоже являются общими типами.

2018-12-28 14:24 UTC, adkozlov commented on EulersProblems/src/main/scala/CommonTypes.scala
> +object CommonTypes {
Это можно в package object было сделать.

2018-12-28 14:24 UTC, adkozlov commented on EulersProblems/src/test/scala/TestTypeProblems.scala
> +import Problem401.{Problem401Scala}
На такие импорты даже среда ругается.

2018-12-28 14:24 UTC, adkozlov commented on EulersProblems/src/test/scala/TestTypeProblems.scala
> +    assert(Problem625Scala.ans(1) == Problem625.toInt[Problem625._1#ProblemSolve])
Лучше использовать всякие `assertEquals` из JUnit.

2018-12-28 14:24 UTC, adkozlov commented on EulersProblems/src/main/scala/Problem401.scala
> +  class NatRep[T <: Nat](val i: Int)
Меня не покидает ощущение, что (по крайней мере) часть из этого списана отсюда:
https://github.com/adkozlov/scala-2018/pull/70/files#diff-6fed6fd05d3ed86e84f7c3493ca5932cR22

2018-12-28 14:24 UTC, adkozlov commented on EulersProblems/src/main/scala/Problem401.scala
> +  class NatRep[T <: Nat](val i: Int)
Или отсюда:
https://github.com/adkozlov/scala-2018/pull/109/files#diff-8a67c7413512e14ff93dcf0d957bf764R64

2018-12-28 14:25 UTC, closed without merging

2018-12-28 14:31 UTC, SashaOrlova commented on EulersProblems/src/main/scala/Problem401.scala
> +  class NatRep[T <: Nat](val i: Int)
Идея про числа действительно у всех троих была взята с https://apocalisp.wordpress.com/2010/06/08/type-level-programming-in-scala/

2018-12-28 14:33 UTC, SashaOrlova commented on EulersProblems/src/test/scala/TestTypeProblems.scala
> +import Problem401.{Problem401Scala}
К сожалению, при включенных инспекциях среда не может адекватно работать и жутко тормозит

2018-12-28 14:33 UTC, adkozlov commented on EulersProblems/src/main/scala/Problem401.scala
> +  class NatRep[T <: Nat](val i: Int)
А, ок.

2018-12-28 14:35 UTC, adkozlov commented on EulersProblems/src/test/scala/TestTypeProblems.scala
> +import Problem401.{Problem401Scala}
Эмм... Попробуйте увеличить хип. Для работы со Scala это бывает необходимо.