HA01, Правилов Михаил
adkozlov/scala-2018 pull request #19
Opened 2018-10-28 13:45 UTC by RamSaw

2018-11-06 21:18 UTC, adkozlov requested changes
Реализация предполагалась через визиторы/листенеры.
Я объявлю, что делать тем, кто делал через атрибуты.

2018-12-11 15:18 UTC, adkozlov reviewed
Замечания стандартные: копипаста, не очень типизированная версия, отсутствие выраженных абстракций.

2018-12-11 15:18 UTC, adkozlov commented on src/main/scala/ru/hse/spb/jvm/scala/CalculatorConsoleApplication.scala
> +      input match {
Можно так:
```
StdIn.readLine() match {
  case "exit" =>
  case input =>
}
```

2018-12-11 15:18 UTC, adkozlov commented on src/main/scala/ru/hse/spb/jvm/scala/CalculatorConsoleApplication.scala
> +            case e: Exception =>
`catch e: Exception`?

2018-12-11 15:18 UTC, adkozlov commented on src/main/scala/ru/hse/spb/jvm/scala/Visitor.scala
> +class Visitor extends CalculatorBaseVisitor[Double] {
Класс stateless.

2018-12-11 15:18 UTC, adkozlov commented on src/main/scala/ru/hse/spb/jvm/scala/Visitor.scala
> +  private val binaryOperationFunctions: Map[String, (Double, Double) => Double] = Map(
Методы могут быть объявлены статическими.

2018-12-11 15:18 UTC, adkozlov commented on src/main/scala/ru/hse/spb/jvm/scala/Visitor.scala
> +    "&&" -> { (a, b) => toDouble(a != 0 && b != 0) }
`_ != 0` написано только здесь 4 раза.

2018-12-11 15:18 UTC, adkozlov commented on src/main/scala/ru/hse/spb/jvm/scala/Visitor.scala
> +    else binaryOperationFunctions(operator.getText).apply(visit(leftOperand), visit(rightOperand))
Явный `apply` писать не принято.
`visit(leftOperand)` происходит в обеих ветках.

2018-12-11 15:19 UTC, closed without merging

2018-12-16 22:07 UTC, RamSaw commented on src/main/scala/ru/hse/spb/jvm/scala/Visitor.scala
> +class Visitor extends CalculatorBaseVisitor[Double] {
Лучше сделать object, да?

2018-12-16 22:08 UTC, RamSaw commented on src/main/scala/ru/hse/spb/jvm/scala/Visitor.scala
> +    "&&" -> { (a, b) => toDouble(a != 0 && b != 0) }
а как можно от этого избавиться?