HA01, Недиков Константин
adkozlov/scala-2018 pull request #26
Opened 2018-10-28 19:02 UTC by kostya55516

2018-11-06 21:19 UTC, adkozlov requested changes
Реализация предполагалась через визиторы/листенеры.
Я объявлю, что делать тем, кто делал через атрибуты.

2018-11-06 21:45 UTC, kostya55516 commented
Ну, мы на Котлине уже писали полноценный интерпретатор, так что это в любом случае было бы неинтересно. Так с тестами поигрались и норм

2018-11-06 21:53 UTC, closed without merging

2018-12-26 17:38 UTC, adkozlov commented on src/test/scala/ru/hse/scala/nedikov/calculator/CalculatorTest.scala
> +  def main(args: Array[String]): Unit = {
`main` в тестах?

2018-12-26 17:38 UTC, adkozlov commented on src/test/scala/ru/hse/scala/nedikov/calculator/CalculatorTest.scala
> +  def test(expected: Boolean, input: String): Unit = {
Почему эти методы публичные?

2018-12-26 17:38 UTC, adkozlov commented on src/test/scala/ru/hse/scala/nedikov/calculator/CalculatorTest.scala
> +    Calculator.evaluate(input) should be(expected)
Почему сравнение происходит со строковым представлением?

2018-12-26 17:38 UTC, adkozlov commented on src/main/scala/ru/hse/scala/nedikov/calculator/Calculator.scala
> +      if (in == ":q") return
Магическая константа.

2018-12-26 17:38 UTC, adkozlov commented on src/main/antlr/Calculator.g4
> +    | bexp=booleanExpression {$value = $bexp.value ? "true" : "false";}
Магические константы из грамматики.

2018-12-26 17:38 UTC, adkozlov commented on src/test/scala/ru/hse/scala/nedikov/calculator/CalculatorTest.scala
> +    test(if (expected) "true" else "false", input)
Эти константы уже встречались в грамматике. То есть определены в коде несколько раз.

2018-12-26 17:38 UTC, adkozlov commented on src/main/scala/ru/hse/scala/nedikov/calculator/Calculator.scala
> +    new CalculatorParser(new BufferedTokenStream(calculatorLexer)).eval().value
Могут ли быть какие-либо исключения?