HA01, Стребежев Игорь
adkozlov/scala-2018 pull request #6
Opened 2018-10-24 15:42 UTC by xamgore

Использовал атрибутную грамматику для вычисления выражений.

2018-11-05 16:56 UTC, adkozlov requested changes
Данное задание предполагало реализацию через визиторы/листнеры.
Для тех, кто использовал атрибуты, я объявлю план действий.

2018-11-05 16:56 UTC, adkozlov commented on src/main/antlr4/a.g4
> +grammar a;
Что отражает данное название?

2018-11-05 16:56 UTC, adkozlov commented on build.sbt
> +enablePlugins(Antlr4Plugin)
Очень хорошо.

2018-11-05 16:56 UTC, adkozlov commented on src/main/antlr4/a.g4
> +      '!=' compare       { $res = ($res != $compare.res) ? 1 : 0; }
Это мало отличается от предыдущей строки.
При данном подходе порождается копипаста.

2018-11-05 16:56 UTC, adkozlov commented on src/main/scala/Main.scala
> +  private def read(): Boolean = {
Это вот все точно `read`?

2018-11-05 16:56 UTC, adkozlov commented on src/main/scala/Main.scala
> +      case ex: RuntimeException => println("Some exception occured")
А можно ли после этого понять, что же все-таки произошло?

2018-11-05 16:56 UTC, adkozlov commented on src/main/scala/Main.scala
> +    new aParser(new CommonTokenStream(new aLexer(CharStreams.fromString(str)))).expr().res
Из-за такого названия грамматики, название парсера совсем странное.

2018-11-05 16:56 UTC, adkozlov commented on src/main/scala/Main.scala
> +    new aParser(new CommonTokenStream(new aLexer(CharStreams.fromString(str)))).expr().res
Лучше разделить это на парсинг и вычисление.

2018-11-25 19:17 UTC, xamgore commented
@adkozlov, я болел две недели (Кузя в курсе), и не мог переписать на визиторы (так чтобы уложиться в дедлайн). Вы не будете против, если я доделаю задание не смотря на дедлайн? У меня просто руки всё никак не дойдут.

2018-11-27 22:08 UTC, adkozlov commented
@xamgore Добрый день. Лучше по таким вопросам писать письмо. :)
Хорошо, давайте так. Дедлайн для Вас: 4 декабря 23:59:59.

2018-12-16 21:32 UTC, adkozlov commented
Антон Михайлович мне сказал, что Ваш комментарий не соответствует действительности.
Прошу решить с ним данный вопрос. (Я пока тогда считаю версию на атрибутах последней.)

2018-12-18 21:26 UTC, xamgore commented
Судя по разговору с АМ стало ясно, что вы не поняли меня и я плохо написал:
* Я болел в пределах 29-го октября `[~неделя, 29, ~неделя]`
* После этого сдавал образованные долги и до скалы _“руки всё никак не доходили”_
* Мне показалось, что, возможно, вы не будете против и разрешите переделать задание
* Кузя *не разрешал* мне пересдавать эту работу, разрешение я спрашивал у вас. Но он был _“в курсе”_ моей болезни.

Будет классно, если вы сможете хотя бы отревьюить решение (как-нибудь потом), если нет, то можно проверить [решение третьего задания](https://github.com/adkozlov/scala-2018/pull/106).

2018-12-24 01:33 UTC, closed without merging