HA01, Халанский Дмитрий
adkozlov/scala-2018 pull request #8
Opened 2018-10-26 13:06 UTC by dkhalansky

2018-11-05 19:21 UTC, adkozlov requested changes
Реализация данного задания предполагалась через визиторы/листенеры.

Я объявлю план действий для тех, кто использовал атрибуты.

2018-11-05 19:21 UTC, adkozlov commented on src/main/scala/Ast.scala
> +package ru.hse.spb.ast
А почему сам файл не лежит в соответствующей директории?

2018-11-05 19:21 UTC, adkozlov commented on src/main/scala/Evaluator.scala
> +    case BinOp(operator, leftOperand, rightOperand) => {
Лишние фигурные скобочки.

2018-11-05 19:21 UTC, adkozlov commented on src/main/scala/Evaluator.scala
> +      val x = eval(left_operand)
В репозитории хочется видеть хотя бы компилирующуюся версию...

2018-11-05 19:21 UTC, adkozlov commented on src/main/scala/Evaluator.scala
> +      val toInt = (b: Boolean) => if (b) { 1 } else { 0 }
Можно убрать фигурные скобки.

2018-11-05 19:21 UTC, adkozlov commented on src/main/scala/Evaluator.scala
> +      operator match {
Этого матча вообще могло бы не быть, если бы решение было оформлено в виде конкретных реализаций `BinOp`.

2018-11-05 19:21 UTC, adkozlov commented on src/test/scala/TestSuite.scala
> +  def getTokenStrings(input: String): List[String] = {
Методы могут быть приватными.

2018-11-05 19:21 UTC, adkozlov commented on src/test/scala/TestSuite.scala
> +    val tokens = lexer.getAllTokens().asScala.toList
Зачем здесь еще конвертация `toList`?

2018-11-05 20:33 UTC, dkhalansky commented on src/test/scala/TestSuite.scala
> +    val tokens = lexer.getAllTokens().asScala.toList
Если я её убираю, компилятор выдаёт ошибку:
```
[error] /home/jvmLangs/scala-2018/src/test/scala/TestSuite.scala:19:15: type mismatch;
[error]  found   : scala.collection.mutable.Buffer[String]
[error]  required: List[String]
[error]     tokens.map(_.getText())
```

2018-11-05 20:35 UTC, dkhalansky commented on src/main/scala/Evaluator.scala
> +      operator match {
Хорошо. Это абстрактное высказывание или требование переоформить решение через набор наследников `BinOp`?

2018-11-05 20:37 UTC, adkozlov commented on src/test/scala/TestSuite.scala
> +    val tokens = lexer.getAllTokens().asScala.toList
Это понятно. `List` используется в качестве возвращаемого типа функции.
Более длинная версия вопроса: зачем возвращать `List`, в который коллекцию еще и конвертировать придется?

2018-11-05 20:44 UTC, adkozlov commented on src/main/scala/Evaluator.scala
> +      operator match {
Это мой ответ на утверждение, которое было выражено в виде комментария.
В целом, я не ставлю _требований_ что-либо переоформить.

2018-11-05 20:46 UTC, adkozlov commented
Советую не торопиться с внесением изменений и пересмотреть всю работу.
Более того, ее все равно нужно будет сделать без атрибутов.

2018-11-05 20:52 UTC, dkhalansky commented on src/main/scala/Evaluator.scala
> +      val toInt = (b: Boolean) => if (b) { 1 } else { 0 }
Не очень понятно, относится этот комментарий к этому конкретному месту или ко всему проекту в целом.
Если к этому месту, то я придумал только один способ добавить сюда больше типов: сделать так, чтобы логические и числовые значения воспринимались интерпретатором по-разному и чтобы вычислитель возвращал `Either[Boolean, Int]`. Типов станет больше, а эта маленькая функция исчезнет.
Если к проекту в целом, то не очень понятно, какие именно абстракции Вам хотелось бы видеть. Пожалуйста, приведите пример. Вы имеете в виду ООП-стиль, со всякими Visitor'ами выражений?

2018-11-05 20:53 UTC, dkhalansky commented on src/main/scala/Evaluator.scala
> +      val x = eval(left_operand)
Простите, пожалуйста, так вышло совершенно случайно.

2018-11-05 21:01 UTC, adkozlov commented on src/main/scala/Evaluator.scala
> +      val toInt = (b: Boolean) => if (b) { 1 } else { 0 }
Да, именно ООП-стиль с визиторами. Во-первых, у нас тема такая была. Во-вторых, именно они используются для синтаксического анализа и обхода древовидных структур.
Хочется, чтобы получаемое дерево можно было типизировать: какие-то узлы типом `Int`, 
 какие-то узлы типом `Boolean`.

Монада `Either` подразумевает не просто два несвязанных варианта, а вычисление, которое могло закончится успешно или не успешно. А объединений типов в Scala 2 пока нет.

2018-12-16 21:29 UTC, adkozlov commented
Сильно лучше не стало. Магические константы как были, так и остались.
Свитч по всем операциям, как был, так и остался.

2018-12-16 21:29 UTC, closed without merging